Create the 3D Array

In [1]:
import numpy as np
data = np.arange(1, 3*16*10 + 1).reshape(3, 16, 10)
print("Shape:", data.shape)
print(data)

Shape: (3, 16, 10)
[[[  1   2   3   4   5   6   7   8   9  10]
  [ 11  12  13  14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27  28  29  30]
  [ 31  32  33  34  35  36  37  38  39  40]
  [ 41  42  43  44  45  46  47  48  49  50]
  [ 51  52  53  54  55  56  57  58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 71  72  73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97  98  99 100]
  [101 102 103 104 105 106 107 108 109 110]
  [111 112 113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128 129 130]
  [131 132 133 134 135 136 137 138 139 140]
  [141 142 143 144 145 146 147 148 149 150]
  [151 152 153 154 155 156 157 158 159 160]]

 [[161 162 163 164 165 166 167 168 169 170]
  [171 172 173 174 175 176 177 178 179 180]
  [181 182 183 184 185 186 187 188 189 190]
  [191 192 193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208 209 210]
  [211 212 213 214 215 216 217 218 219 220]
  [221 222 

Year-wise Average

In [2]:
year_avg = data.mean(axis=(1, 2))
print("Year-wise Average:\n", year_avg)


Year-wise Average:
 [ 80.5 240.5 400.5]


Student-wise Total

In [3]:
student_total = data.sum(axis=2)
print("Student-wise Total:\n", student_total)

Student-wise Total:
 [[  55  155  255  355  455  555  655  755  855  955 1055 1155 1255 1355
  1455 1555]
 [1655 1755 1855 1955 2055 2155 2255 2355 2455 2555 2655 2755 2855 2955
  3055 3155]
 [3255 3355 3455 3555 3655 3755 3855 3955 4055 4155 4255 4355 4455 4555
  4655 4755]]


Subject-wise Highest Score

In [4]:
subject_max = data.max(axis=(0, 1))
print("Subject-wise Highest Score:\n", subject_max)

Subject-wise Highest Score:
 [471 472 473 474 475 476 477 478 479 480]


Replace Marks Below 40 with 40

In [5]:
data[data < 40] = 40
print("Updated Data:\n", data)

Updated Data:
 [[[ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 41  42  43  44  45  46  47  48  49  50]
  [ 51  52  53  54  55  56  57  58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 71  72  73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97  98  99 100]
  [101 102 103 104 105 106 107 108 109 110]
  [111 112 113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128 129 130]
  [131 132 133 134 135 136 137 138 139 140]
  [141 142 143 144 145 146 147 148 149 150]
  [151 152 153 154 155 156 157 158 159 160]]

 [[161 162 163 164 165 166 167 168 169 170]
  [171 172 173 174 175 176 177 178 179 180]
  [181 182 183 184 185 186 187 188 189 190]
  [191 192 193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208 209 210]
  [211 212 213 214 215 216 217 218 219 220]
  [221 222 223 

Sort Marks Subject-wise

In [6]:
sorted_data = np.sort(data, axis=1)
print("Subject-wise Sorted Data:\n", sorted_data)

Subject-wise Sorted Data:
 [[[ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 40  40  40  40  40  40  40  40  40  40]
  [ 41  42  43  44  45  46  47  48  49  50]
  [ 51  52  53  54  55  56  57  58  59  60]
  [ 61  62  63  64  65  66  67  68  69  70]
  [ 71  72  73  74  75  76  77  78  79  80]
  [ 81  82  83  84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97  98  99 100]
  [101 102 103 104 105 106 107 108 109 110]
  [111 112 113 114 115 116 117 118 119 120]
  [121 122 123 124 125 126 127 128 129 130]
  [131 132 133 134 135 136 137 138 139 140]
  [141 142 143 144 145 146 147 148 149 150]
  [151 152 153 154 155 156 157 158 159 160]]

 [[161 162 163 164 165 166 167 168 169 170]
  [171 172 173 174 175 176 177 178 179 180]
  [181 182 183 184 185 186 187 188 189 190]
  [191 192 193 194 195 196 197 198 199 200]
  [201 202 203 204 205 206 207 208 209 210]
  [211 212 213 214 215 216 217 218 219 220]
  [